language: java
install: gradle wrapper --gradle-version 4.2

jdk:
- oraclejdk8

script:
- cd sharingIsCaring/
- chmod =+rwx gradlew
- chmod =+rwx gradle
- ./gradlew build --scan -s
#skript:
#  - ./gradlew check
#  - chmod +x ./gradlew
#  - oraclejdk8
#skript:
#  - TERM=dumb ./gradlew check
# - chmod +x ./gradlew
#service:
#  - docker
#  - postgresql

#before_skript:
#  - cd sharingIsCaring
#  - docker run --rm -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=propra -p 5432:5432 postgres
#  - docker run -p 8888:8888 propra/propay:latest
#script:
#  - ./gradlew build --scan -s
