version: "3.1"
services:
  proxy:
    image: nginx:1.15-alpine
    ports:
    - "8080:8080"
    volumes:
    - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro
    depends_on:
    - propay
    - sharingiscaring

  sharingiscaring:
    build:
      context: ./sharingIsCaring
    volumes:
      - ./sharingIsCaring:/code

  sharingiscaringdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - ./sharingIsCaring/data:/var/lib/postgres/data

    environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=propra
    - POSTGRES_USER=postgres

  propay:
    image: propra/propay
